In [5]:
import pandas as pd

pokemon = pd.read_csv('https://raw.githubusercontent.com/we-b/datasets_for_ai/master/poke.csv')
pokemon.head()

Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed Legendary
0   Bulbasaur    318  45      49       49       65       65     45     False
1     Ivysaur    405  60      62       63       80       80     60     False
2    Venusaur    525  80      82       83      100      100     80     False
3  Charmander    309  39      52       43       60       50     65     False
4  Charmeleon    405  58      64       58       80       65     80     False

In [9]:
import numpy as np
X = np.array(pokemon)
print(X[24, :])

['Pikachu' 320 35 55 40 50 50 90 False]


In [10]:
print("Name HP\n", X[:, [0, 2]])

Name HP
 [['Bulbasaur' 45]
 ['Ivysaur' 60]
 ['Venusaur' 80]
 ['Charmander' 39]
 ['Charmeleon' 58]
 ['Charizard' 78]
 ['Squirtle' 44]
 ['Wartortle' 59]
 ['Blastoise' 79]
 ['Caterpie' 45]
 ['Metapod' 50]
 ['Butterfree' 60]
 ['Weedle' 40]
 ['Kakuna' 45]
 ['Beedrill' 65]
 ['Pidgey' 40]
 ['Pidgeotto' 63]
 ['Pidgeot' 83]
 ['Rattata' 30]
 ['Raticate' 55]
 ['Spearow' 40]
 ['Fearow' 65]
 ['Ekans' 35]
 ['Arbok' 60]
 ['Pikachu' 35]
 ['Raichu' 60]
 ['Sandshrew' 50]
 ['Sandslash' 75]
 ['Nidoran' 55]
 ['Nidorina' 70]
 ['Nidoqueen' 90]
 ['Nidoran' 46]
 ['Nidorino' 61]
 ['Nidoking' 81]
 ['Clefairy' 70]
 ['Clefable' 95]
 ['Vulpix' 38]
 ['Ninetales' 73]
 ['Jigglypuff' 115]
 ['Wigglytuff' 140]
 ['Zubat' 40]
 ['Golbat' 75]
 ['Oddish' 45]
 ['Gloom' 60]
 ['Vileplume' 75]
 ['Paras' 35]
 ['Parasect' 60]
 ['Venonat' 60]
 ['Venomoth' 70]
 ['Diglett' 10]
 ['Dugtrio' 35]
 ['Meowth' 40]
 ['Persian' 65]
 ['Psyduck' 50]
 ['Golduck' 80]
 ['Mankey' 40]
 ['Primeape' 65]
 ['Growlithe' 55]
 ['Arcanine' 90]
 ['Poliwag' 40

In [14]:
# 3行目以降のポケモンを全て取得
print(X[3:], '\n')
# 最初から3行目までを全て取得
print(X[:3])

[['Charmander' 309 39 ..., 50 65 False]
 ['Charmeleon' 405 58 ..., 65 80 False]
 ['Charizard' 534 78 ..., 85 100 False]
 ..., 
 ['Dragonite' 600 91 ..., 100 80 False]
 ['Mewtwo' 680 106 ..., 90 130 True]
 ['Mew' 600 100 ..., 100 100 False]] 

[['Bulbasaur' 318 45 49 49 65 65 45 False]
 ['Ivysaur' 405 60 62 63 80 80 60 False]
 ['Venusaur' 525 80 82 83 100 100 80 False]]


In [16]:
# 全てのデータに関してHPからSpeedまでの情報を取得
X_sliced = X[:, 2:8]
print(X_sliced)
print(X_sliced.shape)

[[45 49 49 65 65 45]
 [60 62 63 80 80 60]
 [80 82 83 100 100 80]
 [39 52 43 60 50 65]
 [58 64 58 80 65 80]
 [78 84 78 109 85 100]
 [44 48 65 50 64 43]
 [59 63 80 65 80 58]
 [79 83 100 85 105 78]
 [45 30 35 20 20 45]
 [50 20 55 25 25 30]
 [60 45 50 90 80 70]
 [40 35 30 20 20 50]
 [45 25 50 25 25 35]
 [65 90 40 45 80 75]
 [40 45 40 35 35 56]
 [63 60 55 50 50 71]
 [83 80 75 70 70 101]
 [30 56 35 25 35 72]
 [55 81 60 50 70 97]
 [40 60 30 31 31 70]
 [65 90 65 61 61 100]
 [35 60 44 40 54 55]
 [60 85 69 65 79 80]
 [35 55 40 50 50 90]
 [60 90 55 90 80 110]
 [50 75 85 20 30 40]
 [75 100 110 45 55 65]
 [55 47 52 40 40 41]
 [70 62 67 55 55 56]
 [90 92 87 75 85 76]
 [46 57 40 40 40 50]
 [61 72 57 55 55 65]
 [81 102 77 85 75 85]
 [70 45 48 60 65 35]
 [95 70 73 95 90 60]
 [38 41 40 50 65 65]
 [73 76 75 81 100 100]
 [115 45 20 45 25 20]
 [140 70 45 85 50 45]
 [40 45 35 30 40 55]
 [75 80 70 65 75 90]
 [45 50 55 75 65 30]
 [60 65 70 85 75 40]
 [75 80 85 110 90 50]
 [35 70 55 45 55 25]
 [60 95 80 60 80 

In [17]:
zero = np.argmax(X_sliced, axis=0)
print(zero)
print(zero.shape)

[112 148  90 149 143 100]
(6,)


In [19]:
one = np.argmax(X_sliced, axis=1)
print(one)
print(one.shape)

[3 3 3 5 3 3 2 2 4 0 2 3 5 2 1 5 5 5 5 5 5 5 1 1 5 5 2 2 0 0 1 1 1 1 0 0 4
 4 0 0 5 5 3 3 3 1 1 0 3 5 5 5 5 3 3 1 1 1 1 5 5 1 3 3 3 1 1 1 1 1 1 4 4 2
 2 2 5 5 0 2 3 3 1 1 1 4 4 0 0 2 2 3 3 3 2 4 4 1 1 5 5 2 3 2 2 1 4 0 2 2 2
 1 0 2 0 2 2 1 1 5 5 4 1 3 5 3 1 5 5 1 0 0 4 0 5 1 3 2 2 2 1 5 0 4 3 3 1 1
 1 3 0]
(151,)


In [20]:
A = X[0:3]
B = X[3:6]
print(A)
print(B)
print(A.shape)
print(B.shape)

[['Bulbasaur' 318 45 49 49 65 65 45 False]
 ['Ivysaur' 405 60 62 63 80 80 60 False]
 ['Venusaur' 525 80 82 83 100 100 80 False]]
[['Charmander' 309 39 52 43 60 50 65 False]
 ['Charmeleon' 405 58 64 58 80 65 80 False]
 ['Charizard' 534 78 84 78 109 85 100 False]]
(3, 9)
(3, 9)


In [21]:
print(np.concatenate((A, B), axis=0))
print(np.concatenate((A, B), axis=0).shape)

[['Bulbasaur' 318 45 49 49 65 65 45 False]
 ['Ivysaur' 405 60 62 63 80 80 60 False]
 ['Venusaur' 525 80 82 83 100 100 80 False]
 ['Charmander' 309 39 52 43 60 50 65 False]
 ['Charmeleon' 405 58 64 58 80 65 80 False]
 ['Charizard' 534 78 84 78 109 85 100 False]]
(6, 9)


In [22]:
print(np.concatenate((A, B), axis=1))
print(np.concatenate((A, B), axis=1).shape)

[['Bulbasaur' 318 45 49 49 65 65 45 False 'Charmander' 309 39 52 43 60 50
  65 False]
 ['Ivysaur' 405 60 62 63 80 80 60 False 'Charmeleon' 405 58 64 58 80 65 80
  False]
 ['Venusaur' 525 80 82 83 100 100 80 False 'Charizard' 534 78 84 78 109 85
  100 False]]
(3, 18)
