In [5]:
import numpy as np
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
list = np.linspace(1,10, 10)
print(list)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
1.0


In [18]:
x = np.linspace(0, 5, 5)
y = np.linspace(6, 10, 5)

print(x, y, "# 結合前のxとyの中身")

xy = np.concatenate([x, y])
print(xy, "xyを結合したxyの中身")

[ 0.    1.25  2.5   3.75  5.  ] [  6.   7.   8.   9.  10.] # 結合前のxとyの中身
[  0.     1.25   2.5    3.75   5.     6.     7.     8.     9.    10.  ] xyを結合したxyの中身


In [25]:
x = np.linspace(1, 10, 10)
print(x)

print(x.max())
print(x.min())
print(x.sum())
#stdは標準偏差を求めてくれる
print(x.std())

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
10.0
1.0
55.0
2.87228132327
